//common
export const SHOW_LOADER = 'COMMON/SHOW_LOADING';
export const HIDE_LOADER = 'COMMON/HIDE_LOADER';

//listing
export const SHOW_INDEX_LOADER = 'LIST/SHOW_INDEX_LOADER';
export const HIDE_INDEX_LOADER = 'LIST/HIDE_INDEX_LOADER';
export const FETCHED_LIST = 'LIST/FETCHED_LIST';
export const NO_DATA = 'LIST/NO_DATA';
export const SET_FAVORITE = 'LIST/SET_FAVORITE';

//details
export const SHOW_DETAILS_LOADER = 'DETAILS/SHOW_DETAILS_LOADER';
export const HIDE_DETAILS_LOADER = 'DETAILS/HIDE_DETAILS_LOADER';
export const FETCH_DETAILS = 'DETAILS/FETCH_DETAILS';
